name: deploy-clojars

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-clojars:
    name: Deploy to Clojars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.0'
          lein: 2.9.5
      - run: lein deploy clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
